// Theme.Product.swift
// Homogeneous product indexed by Theme cases.

import Dimension

extension Theme {
  /// Homogeneous product indexed by theme cases.
  ///
  /// `Theme.Product<V>` represents the exponential object `V^Theme ≅ V × V`,
  /// storing one value per theme case. This is the natural product structure
  /// generated by the finite `Enumerable` type `Theme`.
  ///
  /// ## Example
  ///
  /// ```swift
  /// let colors: Theme.Product<Color> = .init(light: .black, dark: .white)
  ///
  /// // Access by property
  /// colors.light  // .black
  /// colors.dark   // .white
  ///
  /// // Access by theme (uses caseIndex)
  /// colors[.light]  // .black
  /// colors[theme]   // dynamic selection
  ///
  /// // Functor map
  /// let strings = colors.map { $0.description }
  /// ```
  ///
  /// ## Algebra
  ///
  /// - `Theme.Product<V>` ≅ `V²` (binary homogeneous product)
  /// - `product[theme]` is projection `π_{theme.caseIndex}`
  /// - `map` is the functorial action on morphisms
  public struct Product<Value> {
    /// Value for light mode (index 0).
    public var light: Value

    /// Value for dark mode (index 1).
    public var dark: Value

    /// Creates a product with values for each theme.
    @inlinable
    public init(light: Value, dark: Value) {
      self.light = light
      self.dark = dark
    }

    /// Creates a product with the same value for all themes.
    @inlinable
    public init(uniform value: Value) {
      self.light = value
      self.dark = value
    }
  }
}

// MARK: - Subscript Access

extension Theme.Product {
  /// Accesses the value for a given theme.
  ///
  /// Uses `theme.caseIndex` to select the appropriate value.
  @inlinable
  public subscript(theme: Theme) -> Value {
    get {
      switch theme.caseIndex {
      case 0: return light
      case 1: return dark
      default: fatalError("Invalid theme index: \(theme.caseIndex)")
      }
    }
    set {
      switch theme.caseIndex {
      case 0: light = newValue
      case 1: dark = newValue
      default: fatalError("Invalid theme index: \(theme.caseIndex)")
      }
    }
  }
}

// MARK: - Functor (Static Implementation)

extension Theme.Product {
  /// Transforms both values using the given closure.
  @inlinable
  public static func map<NewValue>(
    _ product: Theme.Product<Value>,
    transform: (Value) throws -> NewValue
  ) rethrows -> Theme.Product<NewValue> {
    Theme.Product<NewValue>(
      light: try transform(product.light),
      dark: try transform(product.dark)
    )
  }

  /// Transforms values with access to the theme.
  @inlinable
  public static func mapWithTheme<NewValue>(
    _ product: Theme.Product<Value>,
    transform: (Theme, Value) throws -> NewValue
  ) rethrows -> Theme.Product<NewValue> {
    Theme.Product<NewValue>(
      light: try transform(.light, product.light),
      dark: try transform(.dark, product.dark)
    )
  }
}

// MARK: - Functor (Instance Convenience)

extension Theme.Product {
  /// Transforms both values using the given closure.
  @inlinable
  public func map<NewValue>(
    _ transform: (Value) throws -> NewValue
  ) rethrows -> Theme.Product<NewValue> {
    try Self.map(self, transform: transform)
  }

  /// Transforms values with access to the theme.
  @inlinable
  public func mapWithTheme<NewValue>(
    _ transform: (Theme, Value) throws -> NewValue
  ) rethrows -> Theme.Product<NewValue> {
    try Self.mapWithTheme(self, transform: transform)
  }
}

// MARK: - Zip

extension Theme.Product {
  /// Combines two products into a product of pairs.
  @inlinable
  public static func zip<A, B>(
    _ a: Theme.Product<A>,
    _ b: Theme.Product<B>
  ) -> Theme.Product<(A, B)> where Value == (A, B) {
    Theme.Product<(A, B)>(
      light: (a.light, b.light),
      dark: (a.dark, b.dark)
    )
  }

  /// Combines two products using a combining function.
  @inlinable
  public static func zipWith<A, B>(
    _ a: Theme.Product<A>,
    _ b: Theme.Product<B>,
    combine: (A, B) throws -> Value
  ) rethrows -> Theme.Product<Value> {
    Theme.Product(
      light: try combine(a.light, b.light),
      dark: try combine(a.dark, b.dark)
    )
  }
}

// MARK: - Conditional Conformances

extension Theme.Product: Sendable where Value: Sendable {}
extension Theme.Product: Equatable where Value: Equatable {}
extension Theme.Product: Hashable where Value: Hashable {}

// MARK: - Sequence Conversion

extension Theme.Product {
  /// Returns values as an array in case order (light, dark).
  @inlinable
  public var values: [Value] {
    [light, dark]
  }

  /// Creates a product from an array.
  ///
  /// - Precondition: Array must have exactly 2 elements.
  @inlinable
  public init(values: [Value]) {
    precondition(values.count == Theme.caseCount, "Array must have \(Theme.caseCount) elements")
    self.light = values[0]
    self.dark = values[1]
  }
}
